services:
  memgraph:
    image: memgraph/memgraph-mage:3.9.0
    container_name: memgraph-pyspark
    ports:
      - "7687:7687"
      - "3000:3000"
    command:
      [
        "--telemetry-enabled=false",
        "--log-level=TRACE",
        "--also-log-to-stderr=true",
      ]
