services:
  memgraph:
    image: memgraph/memgraph-mage:3.2
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
      - "9091:9091"
    environment:
      - MEMGRAPH_ORGANIZATION_NAME=<YOUR_ORGANIZATION_NAME>
      - MEMGRAPH_ENTERPRISE_LICENSE=<YOUR_ENTERPRISE_LICENSE>
    command: ["--log-level=TRACE", "--also-log-to-stderr=true"]

  lab:
    image: memgraph/lab:3.2.0
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
      - ENTERPRISE_LICENSE_ORG_NAME=<YOUR_ORGANIZATION_NAME>
      - ENTERPRISE_LICENSE_KEY=<YOUR_ENTERPRISE_LICENSE>