version: "3.8"

services:
  neo4j:
    image: neo4j:5.26-enterprise
    container_name: neo4j
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins

  memgraph:
    image: memgraph/memgraph-mage:3.3
    container_name: memgraph
    ports:
      - "7688:7687"
      - "3000:3000"
    volumes:
      - memgraph_data:/var/lib/memgraph
      - memgraph_logs:/var/log/memgraph
    # Setting query timeout to 0 so the timeout does not happen
    command: [--log-level=TRACE, --also-log-to-stderr=true, --query-execution-timeout-sec=0]

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  memgraph_data:
  memgraph_logs: 